ci: centralizando config do sonar e refinando vitest para lidar com coverage

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,13 +32,10 @@ jobs:
       - name: Rodar testes
         run: npm test -- --watch=false --browsers=chromium --coverage
 
+      - name: Debug Coverage
+        run: ls -R coverage || echo "Coverage not found"
+
       - name: Rodar SonarCloud
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: |
-          npx sonar-scanner \
-            -Dsonar.projectKey=Renato-Cesarr_Eyes-Project-Front \
-            -Dsonar.organization=renato-cesarr \
-            -Dsonar.host.url=https://sonarcloud.io \
-            -Dsonar.token=$SONAR_TOKEN \
-            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
+        run: npx sonar-scanner
